profile:
  pattern: /profile
  controller: User\Controller\Profile

courses:
  pattern: /courses(/page)
  controller: User\Controller\Courses

order:
  pattern: /order/(id)
  controller: User\Controller\Order

#order_return:
#  pattern: /order/return/(id)
#  controller: User\Controller\Order
#  action:
#    '*': ReturnController
#
#order_feedback:
#  pattern: /order/feedback/(id)
#  controller: User\Controller\Order
#  action:
#    '*': FeedbackController

barcode:
  pattern: /order/(id)/barcode
  controller: User\Controller\Order
  action:
    '*': BarcodeController

login:
  pattern: /login
  controller: User\Controller\Login

logout:
  pattern: /logout
  controller: User\Controller\Logout
  action:
    '*': GetController

registration:
  pattern: /registration
  controller: User\Controller\Registration

activation:
  pattern: /activation
  controller: User\Controller\Activation
  action:
    '*': GetController
