system:
    debug: 0
    timezone: 'UTC'
session:
    handler: native
    expire_time: 144000
cache:
    enabled: 0
    storage: file
    handler: serialize
    dir: cache
    time: 15
language:
    debug: 0
    locale: en-GB
    default: en-GB
    format: ini
    path: resources/languages
pay2go:
    test: true
    notify:
mail:
    admin:
        - service@asukademy.com
        # - simon@asukademy.com
    from: service@asukademy.com
