home:
  pattern: '/'
  controller: 'Acme\Controller\Page\'
page:
  pattern: 'page'
  controller: 'Acme\Controller\Page\'
cover:
  pattern: 'cover'
  controller: 'Acme\Controller\Cover\'
user:
  pattern: '/'
  package: wwuser
