courses:
  pattern: /courses(/page)
  controller: Front\Controller\Courses
  requirements:
    page: \d+
category_courses:
  pattern: /courses(/category_alias,page)
  controller: Front\Controller\Courses
  requirements:
    page: \d+
course:
  pattern: /courses/(category_alias)/(alias)
  controller: Front\Controller\Course

stage:
  pattern: /courses/(category_alias)/(course_alias)/(id)
  controller: Front\Controller\Stage

page:
  pattern: (*paths)
  controller: Front\Controller\Page
  action:
    '*': GetController