image:
  pattern: /image
  controller: Front\Controller\Image

courses:
  pattern: /courses(/page)
  controller: Front\Controller\Courses
  requirements:
    page: \d+
category_courses:
  pattern: /courses(/category_alias,page)
  controller: Front\Controller\Courses
  requirements:
    page: \d+
course:
  pattern: /courses/(category_alias)/(alias)
  controller: Front\Controller\Course

stage:
  pattern: /courses/(category_alias)/(course_alias)/(id)
  controller: Front\Controller\Stage

order:
  pattern: /course/plan/order/(plan_id)
  controller: Front\Controller\Order
  requirements:
    plan_id: \d+
  extra:
    auth: true

order_notify:
  pattern: /order/notify
  controller: Front\Controller\Order
  action:
    '*': NotifyController

clean_expired:
  pattern: /order/clean
  controller: Front\Controller\Order
  action:
    '*': CleanController

# Sitemap
sitemap:
    pattern: /sitemap
    controller: Front\Controller\Sitemap

page:
  pattern: (*paths)
  controller: Front\Controller\Page
  action:
    '*': GetController


#about:
#  pattern: /about
#  controller: Front\Controller\Page
#  action:
#    '*': GetController
#  variables:
#    paths: [about]
#
#faq:
#  pattern: /faq
#  controller: Front\Controller\Page
#  action:
#    '*': GetController
#  variables:
#    paths: [faq]
#
#contact:
#  pattern: /contact
#  controller: Front\Controller\Page
#  action:
#    '*': GetController
#  variables:
#    paths: [contact]
#
#index:
#  pattern: /
#  controller: Front\Controller\Page
#  action:
#    '*': GetController