'home':
    pattern: /
    controller: Admin\Controller\Admin
'users':
    pattern: /users
    controller: Admin\Controller\Users

'user':
    pattern: /user(/id)
    controller: Admin\Controller\User

'courses':
    pattern: /courses
    controller: Admin\Controller\Courses

'course':
    pattern: /course(/id)
    controller: Admin\Controller\Course