'home':
    pattern: /
    controller: Admin\Controller\Users

new:
    pattern: /(name)/new
    controller: Admin\Controller\Crud
    action:
        '*': NewController

edit:
    pattern: /(name)/edit/(id)
    controller: Admin\Controller\Crud
    requirements:
        id: \d+
    action:
        '*': EditController
# User
'users':
    pattern: /users(/page)
    controller: Admin\Controller\Users

'user':
    pattern: /user(/id)
    controller: Admin\Controller\User
    requirements:
        id: \d+

# Course
'courses':
    pattern: /courses(/page)
    controller: Admin\Controller\Courses

'course':
    pattern: /course(/id)
    controller: Admin\Controller\Course
    requirements:
        id: \d+

# Stage
stages:
    pattern: /course/(course_id)/stages
    controller: Admin\Controller\Stages
    requirements:
        course_id: \d+

stage:
    pattern: /course/(course_id)/stage(/id)
    controller: Admin\Controller\Stage
    requirements:
        course_id: \d+
        id: \d+

stage_copy:
    pattern: /stage/(id)
    controller: Admin\Controller\Stage
    action:
        '*': CopyController
    requirements:
        id: \d+

# Plan
plans:
    pattern: /course/(course_id)/stage/(stage_id)/plans
    controller: Admin\Controller\Plans
    requirements:
        course_id: \d+
        stage_id: \d+

# Class
classes:
    pattern: /course/(course_id)/stage/(stage_id)/classes
    controller: Admin\Controller\Classes
    requirements:
        course_id: \d+
        stage_id: \d+

# Order
orders:
    pattern: /orders(/page)
    controller: Admin\Controller\Orders

order:
    pattern: /order(/id)
    controller: Admin\Controller\Order

order_state:
    pattern: /order/state/update/(id)
    controller: Admin\Controller\Order
    action:
        '*': StateController

# Tutor
tutors:
    pattern: /tutors(/page)
    controller: Admin\Controller\Tutors
tutor:
    pattern: /tutor(/id)
    controller: Admin\Controller\Tutor

# Position
positions:
    pattern: /positions(/page)
    controller: Admin\Controller\Positions
position:
    pattern: /position(/id)
    controller: Admin\Controller\Position

# Category
categories:
    pattern: /categories(/page)
    controller: Admin\Controller\Categories
category:
    pattern: /category(/id)
    controller: Admin\Controller\Category